version: '3.6'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongo
      - elasticsearch

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node

  telegraf:
    platform: linux/amd64
    image: telegraf:1.29-alpine
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - mongo
      - elasticsearch
    ports:
      - '8125:8125/udp'

  influxdb:
    platform: linux/amd64
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/


volumes:
  grafana_data: {}
  influxdb_data: {}
