development:
  clients:
    default:
      database: tig_stack_development
      hosts:
        - mongo:27017
      options:
        connect: :direct

test:
  clients:
    default:
      database: tig_stack_test
      hosts:
        - mongo:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
